"""add new table

Revision ID: 9e278ad11742
Revises: e623a7872cd7
Create Date: 2026-01-16 20:57:30.983644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e278ad11742'
down_revision: Union[str, Sequence[str], None] = 'e623a7872cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['friends.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['friend_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friend_group_members')
    # ### end Alembic commands ###
